#ifndef TGX_BENCHMARK3D_CPU_BOARD_CONFIG_H
#define TGX_BENCHMARK3D_CPU_BOARD_CONFIG_H

#define TGX_BENCH_BOARD_NAME "cpu"
#define TGX_BENCH_PROFILE_NAME "cpu-medium"
#define TGX_BENCH_POWER_CLASS 10
#define TGX_BENCH_DEFAULT_WIDTH 320
#define TGX_BENCH_DEFAULT_HEIGHT 240
#define TGX_BENCH_MIN_FRAMES 5
#define TGX_BENCH_MAX_FRAMES 2000
#define TGX_BENCH_TARGET_US 200000UL
#define TGX_BENCH_FAST_ARENA_BYTES (512UL * 1024UL)
#define TGX_BENCH_BULK_ARENA_BYTES (8UL * 1024UL * 1024UL)
#define TGX_BENCH_SUPPORT_HEAVY_MESHES 1
#define TGX_BENCH_SUPPORT_TWO_SPOTLIGHTS 1

#endif
