#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : bob
// Symbol       : bob
// Color type   : tgx::RGB565
// Triangles    : 10688
// Meshlets     : 235
// Materials    : 1
// Chains       : 826 (7.73% of triangles)
// Vertex refs  : 12340 (1.155 per triangle)
// Payload      : 172172 bytes (43043 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 172172 bytes
//   meshlet array : 5640 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 177892 bytes
// Bounding box : x[-1, 1] y[-0.523999489, 0.523999489] z[-0.788369683, 0.788369683]

extern const tgx::Mesh3Dv2<tgx::RGB565> bob;
