#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : spot
// Symbol       : spot
// Color type   : tgx::RGB565
// Triangles    : 5856
// Meshlets     : 128
// Materials    : 1
// Chains       : 469 (8.01% of triangles)
// Vertex refs  : 6794 (1.160 per triangle)
// Payload      : 93240 bytes (23310 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 93240 bytes
//   meshlet array : 3072 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 96392 bytes
// Bounding box : x[-0.548983677, 0.548983677] y[-0.984004391, 0.984004391] z[-1, 1]

extern const tgx::Mesh3Dv2<tgx::RGB565> spot;
