#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : blub
// Symbol       : blub
// Color type   : tgx::RGB565
// Triangles    : 14208
// Meshlets     : 262
// Materials    : 1
// Chains       : 965 (6.79% of triangles)
// Vertex refs  : 16138 (1.136 per triangle)
// Payload      : 216100 bytes (54025 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 216100 bytes
//   meshlet array : 6288 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 222468 bytes
// Bounding box : x[-0.489267532, 0.489267532] y[-0.600741057, 0.600741057] z[-1, 1]

extern const tgx::Mesh3Dv2<tgx::RGB565> blub;
