from __future__ import annotations

import math
import re
from dataclasses import dataclass

from .mesh import FaceVertex, Meshlet, ObjMesh
from .stripifier import DEFAULT_LKH_EXE
from .exporter import _make_chains


@dataclass
class LegacyExportResult:
    header: str
    chains: int
    face_words: int


def _identifier(name: str) -> str:
    out = re.sub(r"\W+", "_", name.strip())
    if not out:
        out = "mesh"
    if out[0].isdigit():
        out = "_" + out
    return out


def _fmt_float(v: float) -> str:
    if not math.isfinite(v):
        return "0.0f"
    text = f"{float(v):.9g}"
    if "e" not in text and "E" not in text and "." not in text:
        text += ".0"
    return text + "f"


def _fmt_vec(values) -> str:
    return "{ " + ", ".join(_fmt_float(float(x)) for x in values) + " }"


def export_legacy_mesh3d_header(
    mesh: ObjMesh,
    *,
    name: str,
    color_type: str = "tgx::RGB565",
    meshlets: list[Meshlet] | None = None,
    use_lkh: bool = True,
    lkh_exe=DEFAULT_LKH_EXE,
) -> LegacyExportResult:
    """Export a Mesh3D validation reference.

    When meshlets are provided, the face stream is generated with the same meshlet order and
    triangle strips as Mesh3D2. This makes pixel-exact comparisons meaningful: the only intended
    difference is that Mesh3D2 may skip invisible meshlets before reading their payload.
    """
    symbol = _identifier(name)
    has_texcoords = mesh.has_texcoords()
    has_normals = mesh.has_normals()
    elem_words = 1 + (1 if has_texcoords else 0) + (1 if has_normals else 0)
    chains = _build_reference_chains(mesh, meshlets, use_lkh=use_lkh, lkh_exe=lkh_exe)
    chain_count = len(chains)
    face_words = 1 + sum(1 + (len(chain) + 2) * elem_words for chain in chains)

    bb_min, bb_max = mesh.bounding_box()
    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <tgx.h>")
    lines.append("")
    lines.append(f"// Mesh3D validation reference generated by tools/mesh3d2_converter.")
    lines.append(f"// Triangles: {len(mesh.triangles)}, chains: {chain_count}.")
    lines.append("")

    lines.append(f"const tgx::fVec3 {symbol}_vert_array[{len(mesh.vertices)}] PROGMEM = {{")
    for v in mesh.vertices:
        lines.append(f"    {_fmt_vec(v)},")
    lines.append("};")
    lines.append("")

    tex_name = "nullptr"
    if has_texcoords:
        tex_name = f"{symbol}_tex_array"
        lines.append(f"const tgx::fVec2 {tex_name}[{len(mesh.texcoords)}] PROGMEM = {{")
        for vt in mesh.texcoords:
            lines.append(f"    {_fmt_vec(vt)},")
        lines.append("};")
        lines.append("")

    norm_name = "nullptr"
    if has_normals:
        norm_name = f"{symbol}_norm_array"
        lines.append(f"const tgx::fVec3 {norm_name}[{len(mesh.normals)}] PROGMEM = {{")
        for n in mesh.normals:
            lines.append(f"    {_fmt_vec(n)},")
        lines.append("};")
        lines.append("")

    lines.append(f"const uint16_t {symbol}_face[{face_words}] PROGMEM = {{")
    for chain in chains:
        lines.append(f"{len(chain)},")
        first = chain[0][1]
        lines.append(_face_corner(first[0], has_texcoords, has_normals))
        lines.append(_face_corner(first[1], has_texcoords, has_normals))
        lines.append(_face_corner(first[2], has_texcoords, has_normals))
        for direction, tri in chain[1:]:
            assert direction is not None
            lines.append(_face_corner(tri[2], has_texcoords, has_normals, direction=direction))
    lines.append("0")
    lines.append("};")
    lines.append("")

    lines.append(f"const tgx::Mesh3D<{color_type}> {symbol} =")
    lines.append("    {")
    lines.append("    1,")
    lines.append(f"    {len(mesh.vertices)},")
    lines.append(f"    {len(mesh.texcoords) if has_texcoords else 0},")
    lines.append(f"    {len(mesh.normals) if has_normals else 0},")
    lines.append(f"    {len(mesh.triangles)},")
    lines.append(f"    {face_words},")
    lines.append(f"    {symbol}_vert_array,")
    lines.append(f"    {tex_name},")
    lines.append(f"    {norm_name},")
    lines.append(f"    {symbol}_face,")
    lines.append("    nullptr,")
    lines.append("    { 0.75f, 0.75f, 0.75f },")
    lines.append("    0.1f,")
    lines.append("    0.7f,")
    lines.append("    0.6f,")
    lines.append("    32,")
    lines.append("    nullptr,")
    lines.append("    {")
    lines.append(f"    {_fmt_float(bb_min[0])}, {_fmt_float(bb_max[0])},")
    lines.append(f"    {_fmt_float(bb_min[1])}, {_fmt_float(bb_max[1])},")
    lines.append(f"    {_fmt_float(bb_min[2])}, {_fmt_float(bb_max[2])}")
    lines.append("    },")
    lines.append(f"    \"{symbol}\"")
    lines.append("    };")
    lines.append("")
    return LegacyExportResult("\n".join(lines), chain_count, face_words)


def _build_reference_chains(mesh: ObjMesh, meshlets: list[Meshlet] | None, *, use_lkh: bool, lkh_exe) -> list:
    if meshlets is None:
        return [[(None, tri.corners)] for tri in mesh.triangles]

    chains = []
    for meshlet in meshlets:
        chains.extend(_make_chains(mesh, meshlet.triangles, use_lkh=use_lkh, lkh_exe=lkh_exe))
    return chains


def _face_corner(corner: FaceVertex, has_texcoords: bool, has_normals: bool, *, direction: int = 0) -> str:
    v = corner.v | (32768 if direction else 0)
    parts = [str(v)]
    if has_texcoords:
        parts.append(str(corner.vt))
    if has_normals:
        parts.append(str(corner.vn))
    return ", ".join(parts) + ","
