#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : naruto_v2
// Symbol       : naruto_v2
// Color type   : tgx::RGB565
// Triangles    : 2472
// Meshlets     : 121
// Materials    : 3
// Chains       : 351 (14.20% of triangles)
// Vertex refs  : 3174 (1.284 per triangle)
// Payload      : 47072 bytes (11768 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 47072 bytes
//   meshlet array : 2904 bytes
//   material array: 96 bytes
//   mesh structure: 48 bytes
//   total         : 50120 bytes
// Bounding box : x[-0.802069302, 0.802069302] y[-1, 1] z[-0.195223555, 0.195223555]

extern const tgx::Mesh3Dv2<tgx::RGB565> naruto_v2;
