name=tgx
version=1.1.0
author=Arvind Singh
maintainer=Arvind Singh
sentence=A tiny 2D and 3D graphics library. 
paragraph=TGX is a tiny but full-featured C++ graphics library for 2D graphics and 3D graphics. It runs on 32-bit CPUs and MCUs such as Teensy, ESP32, Pico/RP2040/RP2350 and desktop CPUs. TGX provides an extensive set of 2D drawing primitives and software 3D rendering with advanced options: mesh support, textures, anti-aliasing, alpha blending... The library itself is hardware-agnostic and draws into a memory framebuffer. An independent display driver is required to show the framebuffer on a physical screen.
category=Display
url=https://github.com/vindar/tgx
architectures=*

