#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : dennis_v2
// Symbol       : dennis_v2
// Color type   : tgx::RGB565
// Triangles    : 7657
// Meshlets     : 190
// Materials    : 1
// Chains       : 787 (10.28% of triangles)
// Vertex refs  : 9231 (1.206 per triangle)
// Payload      : 128404 bytes (32101 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 128404 bytes
//   meshlet array : 4560 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 133044 bytes
// Bounding box : x[-0.34155454, 0.34155454] y[-1, 1] z[-0.243315662, 0.243315662]

extern const tgx::Mesh3Dv2<tgx::RGB565> dennis_v2;
