#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : nanosuit_v2
// Symbol       : nanosuit_v2
// Color type   : tgx::RGB565
// Triangles    : 8807
// Meshlets     : 304
// Materials    : 7
// Chains       : 1042 (11.83% of triangles)
// Vertex refs  : 10891 (1.237 per triangle)
// Payload      : 154400 bytes (38600 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 154400 bytes
//   meshlet array : 7296 bytes
//   material array: 224 bytes
//   mesh structure: 48 bytes
//   total         : 161968 bytes
// Bounding box : x[-0.549127351, 0.549127351] y[-1, 1] z[-0.248331383, 0.248331383]

extern const tgx::Mesh3Dv2<tgx::RGB565> nanosuit_v2;
