#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : elementalist_v2
// Symbol       : elementalist_v2
// Color type   : tgx::RGB565
// Triangles    : 5013
// Meshlets     : 209
// Materials    : 3
// Chains       : 610 (12.17% of triangles)
// Vertex refs  : 6233 (1.243 per triangle)
// Payload      : 91120 bytes (22780 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 91120 bytes
//   meshlet array : 5016 bytes
//   material array: 96 bytes
//   mesh structure: 48 bytes
//   total         : 96280 bytes
// Bounding box : x[-0.496437751, 0.496437751] y[-1, 1] z[-0.319972199, 0.319972199]

extern const tgx::Mesh3Dv2<tgx::RGB565> elementalist_v2;
