#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : skull_1
// Symbol       : skull_1
// Color type   : tgx::RGB565
// Triangles    : 9535
// Meshlets     : 416
// Materials    : 1
// Chains       : 1006 (10.55% of triangles)
// Vertex refs  : 11547 (1.211 per triangle)
// Payload      : 127568 bytes (31892 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 127568 bytes
//   meshlet array : 9984 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 137632 bytes
// Bounding box : x[-0.860172569, 0.860172569] y[-1, 1] z[-0.677500982, 0.677500982]

extern const tgx::Mesh3Dv2<tgx::RGB565> skull_1;
