#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : sinbad_v2
// Symbol       : sinbad_v2
// Color type   : tgx::RGB565
// Triangles    : 7610
// Meshlets     : 260
// Materials    : 3
// Chains       : 744 (9.78% of triangles)
// Vertex refs  : 9098 (1.196 per triangle)
// Payload      : 124304 bytes (31076 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 124304 bytes
//   meshlet array : 6240 bytes
//   material array: 96 bytes
//   mesh structure: 48 bytes
//   total         : 130688 bytes
// Bounding box : x[-0.756263923, 0.756263923] y[-1, 1] z[-0.419043252, 0.419043252]

extern const tgx::Mesh3Dv2<tgx::RGB565> sinbad_v2;
