#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : manga3_v2
// Symbol       : manga3_v2
// Color type   : tgx::RGB565
// Triangles    : 13427
// Meshlets     : 733
// Materials    : 3
// Chains       : 1542 (11.48% of triangles)
// Vertex refs  : 16511 (1.230 per triangle)
// Payload      : 268256 bytes (67064 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 268256 bytes
//   meshlet array : 17592 bytes
//   material array: 96 bytes
//   mesh structure: 48 bytes
//   total         : 285992 bytes
// Bounding box : x[-0.415031443, 0.415031443] y[-1, 1] z[-0.444038457, 0.444038457]

extern const tgx::Mesh3Dv2<tgx::RGB565> manga3_v2;
