#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : suzanne
// Symbol       : suzanne
// Color type   : tgx::RGB565
// Triangles    : 15744
// Meshlets     : 568
// Materials    : 1
// Chains       : 1800 (11.43% of triangles)
// Vertex refs  : 19344 (1.229 per triangle)
// Payload      : 279280 bytes (69820 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 279280 bytes
//   meshlet array : 13632 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 292992 bytes
// Bounding box : x[-1, 1] y[-0.719569409, 0.719569409] z[-0.60374439, 0.60374439]

extern const tgx::Mesh3Dv2<tgx::RGB565> suzanne;
