#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : teapot
// Symbol       : teapot
// Color type   : tgx::RGB565
// Triangles    : 2256
// Meshlets     : 87
// Materials    : 1
// Chains       : 191 (8.47% of triangles)
// Vertex refs  : 2638 (1.169 per triangle)
// Payload      : 29328 bytes (7332 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 29328 bytes
//   meshlet array : 2088 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 31496 bytes
// Bounding box : x[-1, 1] y[-0.489919327, 0.489919327] z[-0.62211978, 0.62211978]

extern const tgx::Mesh3Dv2<tgx::RGB565> teapot;
