#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : stormtrooper_v2
// Symbol       : stormtrooper_v2
// Color type   : tgx::RGB565
// Triangles    : 6518
// Meshlets     : 172
// Materials    : 1
// Chains       : 701 (10.75% of triangles)
// Vertex refs  : 7920 (1.215 per triangle)
// Payload      : 111828 bytes (27957 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 111828 bytes
//   meshlet array : 4128 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 116036 bytes
// Bounding box : x[-0.567079769, 0.567079769] y[-1, 1] z[-0.213310177, 0.213310177]

extern const tgx::Mesh3Dv2<tgx::RGB565> stormtrooper_v2;
