#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : falcon_vs_v2
// Symbol       : falcon_vs_v2
// Color type   : tgx::RGB565
// Triangles    : 6684
// Meshlets     : 317
// Materials    : 20
// Chains       : 935 (13.99% of triangles)
// Vertex refs  : 8554 (1.280 per triangle)
// Payload      : 116820 bytes (29205 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 116820 bytes
//   meshlet array : 7608 bytes
//   material array: 640 bytes
//   mesh structure: 48 bytes
//   total         : 125116 bytes
// Bounding box : x[-0.713262901, 0.713262901] y[-0.219891878, 0.219891878] z[-1, 1]

extern const tgx::Mesh3Dv2<tgx::RGB565> falcon_vs_v2;
