#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : bunny
// Symbol       : bunny
// Color type   : tgx::RGB565
// Triangles    : 4968
// Meshlets     : 175
// Materials    : 1
// Chains       : 353 (7.11% of triangles)
// Vertex refs  : 5674 (1.142 per triangle)
// Payload      : 60764 bytes (15191 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 60764 bytes
//   meshlet array : 4200 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 65044 bytes
// Bounding box : x[-1, 1] y[-0.99050588, 0.99050588] z[-0.775936586, 0.775936586]

extern const tgx::Mesh3Dv2<tgx::RGB565> bunny;
