#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : cyborg_v2
// Symbol       : cyborg_v2
// Color type   : tgx::RGB565
// Triangles    : 5549
// Meshlets     : 153
// Materials    : 1
// Chains       : 512 (9.23% of triangles)
// Vertex refs  : 6573 (1.185 per triangle)
// Payload      : 94160 bytes (23540 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 94160 bytes
//   meshlet array : 3672 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 97912 bytes
// Bounding box : x[-0.860625892, 0.860625892] y[-1, 1] z[-0.230755357, 0.230755357]

extern const tgx::Mesh3Dv2<tgx::RGB565> cyborg_v2;
