#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : buddha
// Symbol       : buddha
// Color type   : tgx::RGB565
// Triangles    : 20000
// Meshlets     : 751
// Materials    : 1
// Chains       : 1636 (8.18% of triangles)
// Vertex refs  : 23272 (1.164 per triangle)
// Payload      : 251432 bytes (62858 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 251432 bytes
//   meshlet array : 18024 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 269536 bytes
// Bounding box : x[-0.501618464, 0.501618464] y[-1, 1] z[-0.39971945, 0.39971945]

extern const tgx::Mesh3Dv2<tgx::RGB565> buddha;
