#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : dragon
// Symbol       : dragon
// Color type   : tgx::RGB565
// Triangles    : 23000
// Meshlets     : 941
// Materials    : 1
// Chains       : 1962 (8.53% of triangles)
// Vertex refs  : 26924 (1.171 per triangle)
// Payload      : 290076 bytes (72519 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 290076 bytes
//   meshlet array : 22584 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 312740 bytes
// Bounding box : x[-0.446471949, 0.446471949] y[-0.704998196, 0.704998196] z[-1, 1]

extern const tgx::Mesh3Dv2<tgx::RGB565> dragon;
