#ifndef TGX_BENCHMARK3D_ESPIDF_BOARD_CONFIG_H
#define TGX_BENCHMARK3D_ESPIDF_BOARD_CONFIG_H

#include <sdkconfig.h>

#if defined(CONFIG_IDF_TARGET_ESP32P4)
    #define TGX_BENCH_BOARD_NAME "esp32p4"
    #define TGX_BENCH_POWER_CLASS 8
#elif defined(CONFIG_IDF_TARGET_ESP32S3)
    #define TGX_BENCH_BOARD_NAME "esp32s3-idf"
    #define TGX_BENCH_POWER_CLASS 5
#elif defined(CONFIG_IDF_TARGET_ESP32S2)
    #define TGX_BENCH_BOARD_NAME "esp32s2-idf"
    #define TGX_BENCH_POWER_CLASS 3
#elif defined(CONFIG_IDF_TARGET_ESP32)
    #define TGX_BENCH_BOARD_NAME "esp32-idf"
    #define TGX_BENCH_POWER_CLASS 4
#else
    #define TGX_BENCH_BOARD_NAME "espidf"
    #define TGX_BENCH_POWER_CLASS 4
#endif

#define TGX_BENCH_PROFILE_NAME "espidf"
#define TGX_BENCH_DEFAULT_WIDTH 160
#define TGX_BENCH_DEFAULT_HEIGHT 120
#define TGX_BENCH_MIN_FRAMES 3
#define TGX_BENCH_MAX_FRAMES 600
#define TGX_BENCH_TARGET_US 250000UL
#define TGX_BENCH_FAST_ARENA_BYTES (32UL * 1024UL)
#define TGX_BENCH_BULK_ARENA_BYTES (512UL * 1024UL)
#define TGX_BENCH_SUPPORT_HEAVY_MESHES 1
#define TGX_BENCH_SUPPORT_TWO_SPOTLIGHTS 1
#define TGX_BENCH_SERIAL_STARTUP_DELAY_MS 2500

#endif
