#pragma once

#include <tgx.h>

// Mesh3Dv2 generated by tools/mesh3d2_converter.
// Source model : R2D2_v2
// Symbol       : R2D2_v2
// Color type   : tgx::RGB565
// Triangles    : 8035
// Meshlets     : 565
// Materials    : 1
// Chains       : 1869 (23.26% of triangles)
// Vertex refs  : 11773 (1.465 per triangle)
// Payload      : 170688 bytes (42672 uint32 words)
// Static memory estimate, excluding texture images:
//   payload array : 170688 bytes
//   meshlet array : 13560 bytes
//   material array: 32 bytes
//   mesh structure: 48 bytes
//   total         : 184328 bytes
// Bounding box : x[-0.593246129, 0.593246129] y[-1, 1] z[-0.465025661, 0.465025661]

extern const tgx::Mesh3Dv2<tgx::RGB565> R2D2_v2;
